{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/device/unlock": {
      "post": {
        "tags": [
          "device-api"
        ],
        "summary": "unlocks device ",
        "operationId": "unlock",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeviceIdAdditionalData"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseFixIssuesResponse"
                }
              }
            }
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseVoid"
                }
              }
            }
          }
        }
      }
    },
    "/device/issue/fix": {
      "post": {
        "tags": [
          "device-api"
        ],
        "summary": "fixes device issue(s) ",
        "operationId": "fixIssues",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeviceIdAdditionalData"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseFixIssuesResponse"
                }
              }
            }
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseVoid"
                }
              }
            }
          }
        }
      }
    },
    "/device/diagnose": {
      "post": {
        "tags": [
          "device-api"
        ],
        "summary": "diagnose device and return issues if there are any",
        "operationId": "diagnose",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeviceIdAdditionalData"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseDiagnosisResponse"
                }
              }
            }
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseVoid"
                }
              }
            }
          }
        }
      }
    },
    "/device": {
      "get": {
        "tags": [
          "device-api"
        ],
        "summary": "Filters and returns enrolled devices based on searchString, searchString request param is optional. if the searchString is passed, filters devices based on searchString. if no devices found return error response(success = false) with messageCodes",
        "operationId": "findAll",
        "parameters": [
          {
            "name": "searchString",
            "in": "query",
            "description": "String to be searched either in device name or serial number ",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseListDeviceInfo"
                }
              }
            }
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseVoid"
                }
              }
            }
          }
        }
      }
    },
    "/device/{deviceId}": {
      "get": {
        "tags": [
          "device-api"
        ],
        "summary": "returns details of a device by deviceId",
        "operationId": "details",
        "parameters": [
          {
            "name": "deviceId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseDeviceDetails"
                }
              }
            }
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseVoid"
                }
              }
            }
          }
        }
      }
    },
    "/config/issues/instructions": {
      "get": {
        "tags": [
          "config-api"
        ],
        "description": "returns device issues and instruction json data",
        "operationId": "getIssueInstructions",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseMapObjectObject"
                }
              }
            }
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseVoid"
                }
              }
            }
          }
        }
      }
    },
    "/": {
      "get": {
        "tags": [
          "health-api"
        ],
        "operationId": "checkHealth_1",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseVoid"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ApiResponseVoid": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "messageCodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "body": {
            "type": "object"
          }
        }
      },
      "DeviceIdAdditionalData": {
        "type": "object",
        "properties": {
          "deviceId": {
            "type": "string"
          },
          "additionalData": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        }
      },
      "ApiResponseFixIssuesResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "messageCodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "body": {
            "$ref": "#/components/schemas/FixIssuesResponse"
          }
        }
      },
      "FixIssuesResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "errors": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "ApiResponseDiagnosisResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "messageCodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "body": {
            "$ref": "#/components/schemas/DiagnosisResponse"
          }
        }
      },
      "DiagnosisResponse": {
        "type": "object",
        "properties": {
          "vendor": {
            "type": "string",
            "enum": [
              "JAMF",
              "MOBILE_IRON"
            ]
          },
          "issues": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Issue"
            }
          },
          "failedTests": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "OS_OUTDATED",
                "CERT_EXPIRED",
                "APP_OUTDATED"
              ]
            }
          },
          "allTests": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "OS_OUTDATED",
                "CERT_EXPIRED",
                "APP_OUTDATED"
              ]
            }
          }
        }
      },
      "Issue": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "enum": [
              "OS_OUTDATED",
              "CERT_EXPIRED",
              "APP_OUTDATED"
            ]
          },
          "additionalData": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          }
        }
      },
      "ApiResponseListDeviceInfo": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "messageCodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "body": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/DeviceInfo"
            }
          }
        }
      },
      "DeviceInfo": {
        "type": "object",
        "properties": {
          "serialNumber": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "model": {
            "type": "string"
          },
          "lastOnline": {
            "type": "string",
            "format": "date-time"
          },
          "warning": {
            "type": "string",
            "enum": [
              "NO",
              "YELLOW",
              "RED"
            ]
          },
          "udid": {
            "type": "string"
          },
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "osVersion": {
            "type": "string"
          },
          "supervised": {
            "type": "string"
          },
          "passcodeStatus": {
            "type": "string"
          },
          "lastEnrollmentTime": {
            "type": "string",
            "format": "date-time"
          },
          "wifiMacAddress": {
            "type": "string"
          },
          "managed": {
            "type": "string"
          },
          "timezone": {
            "type": "string"
          },
          "lastModeEnabled": {
            "type": "string"
          },
          "store": {
            "type": "string"
          },
          "ipAddress": {
            "type": "string"
          },
          "tethered": {
            "type": "string"
          }
        }
      },
      "ApiResponseDeviceDetails": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "messageCodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "body": {
            "$ref": "#/components/schemas/DeviceDetails"
          }
        }
      },
      "DeviceDetails": {
        "type": "object"
      },
      "ApiResponseMapObjectObject": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "messageCodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "body": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          }
        }
      }
    }
  }
}
