{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/device": {
      "get": {
        "tags": [
          "device-api"
        ],
        "summary": "Filters and returns enrolled devices based on searchString, searchString request param is optional. if the searchString is passed, filters devices based on searchString. if no devices found return error response(success = false) with messageCodes",
        "operationId": "findAll",
        "parameters": [
          {
            "name": "searchString",
            "in": "query",
            "description": "String to be searched either in device name or serial number ",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseListDeviceInfo"
                }
              }
            }
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseVoid"
                }
              }
            }
          }
        }
      }
    },
    "/": {
      "get": {
        "tags": [
          "health-api"
        ],
        "operationId": "checkHealth_1",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseVoid"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ApiResponseVoid": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "messageCodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "body": {
            "type": "object"
          }
        }
      },
      "ApiResponseListDeviceInfo": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "messageCodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "body": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/DeviceInfo"
            }
          }
        }
      },
      "DeviceInfo": {
        "type": "object",
        "properties": {
          "serialNumber": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "model": {
            "type": "string"
          },
          "lastOnline": {
            "type": "string",
            "format": "date-time"
          },
          "warning": {
            "type": "string",
            "enum": [
              "NO",
              "YELLOW",
              "RED"
            ]
          },
          "udid": {
            "type": "string"
          },
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "osVersion": {
            "type": "string"
          },
          "supervised": {
            "type": "string"
          },
          "passcodeStatus": {
            "type": "string"
          },
          "lastEnrollmentTime": {
            "type": "string",
            "format": "date-time"
          },
          "wifiMacAddress": {
            "type": "string"
          },
          "managed": {
            "type": "string"
          },
          "timezone": {
            "type": "string"
          },
          "lastModeEnabled": {
            "type": "string"
          },
          "store": {
            "type": "string"
          },
          "ipAddress": {
            "type": "string"
          },
          "tethered": {
            "type": "string"
          }
        }
      }
    }
  }
}
